### ISSUE TITLE
Factor predictors

### ISSUE THREAD

**Issue by tvatter** [swager/gradient-forest#27]
Hi,

I was trying to use your method to predict sales in a grocery store, and my data contains more than a few factor predictors. Some of them can easily be converted to numeric (e.g., hour of day), but some of them should really be treated as categorical (e.g. holiday or not).

An example is the following:
```
library(gradient.forest)

# Sample size
n = 1e3

# A data.frame with customers/holidays, respectively numeric/factor predictors
predictors = data.frame(customers = rnorm(n), 
                        holidays = factor(rbinom(n, 1, 1/10)))

# Sales as a function of customers and holidays
sales = X$customers * rnorm(n) + as.numeric(levels(X$holidays)) * rnorm(n)

q.forest = quantile.forest(predictors, sales, quantiles=c(0.1, 0.5, 0.9))
```
Unfortunately, I get:
```
Error in quantile_train(quantiles, input.data, outcome.index.zeroindexed,  : 
  not compatible with requested type
```
One obvious fix is to convert the factor predictors to numeric, which means that they will be treated as continuous variables, but is it really "correct" to do that?

**Comment by swager** [comment]
Sorry for not having support for factors built in yet; we plan to add such support in the near future. For now, a quick fix is to expand out factors by hand using the ```model.matrix``` command:

```R
X = data.frame(A=rnorm(20), B=factor(sample(1:3, 20, replace = TRUE)))
X.expanded = model.matrix(~ . + 0, data = X)
```

Then you can use ```X.expanded``` as a design matrix for the forest.

**Comment by tvatter** [comment]
No problem, that's a neat solution, I should have thought of it.
