### ISSUE TITLE
getting an error from causal.forest running an example

### ISSUE THREAD

**Issue by sofiav23** [swager/gradient-forest#36]
I installed successfully gradient-forest package on my Mac, but was getting an error while running  test example provided in the repository documentation.

> tau.forest = causal.forest(X, Y, W)
Error in Y - Y.hat : non-numeric argument to binary operator

error comes from causal.forest.R function, line 96 of the code:
input.data <- as.matrix(cbind(X, Y - Y.hat, W - W.hat))

**Comment by swager** [comment]
Sorry! It looks like we introduced a bug while making changes this afternoon, and that code path wasn't under test coverage... It should be fixed now, in pull request #37
